/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import java.awt.print.PrinterException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.*;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Row;
/**
 *
 * @author RTM
 */
public class Reports extends javax.swing.JPanel {

  
    public Reports() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Print_jButton = new javax.swing.JButton();
        customer_jButton = new javax.swing.JButton();
        contract_jButton = new javax.swing.JButton();
        export_jComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        Print_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/Printer-16.png"))); // NOI18N
        Print_jButton.setText("Print");
        Print_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_jButtonActionPerformed(evt);
            }
        });

        customer_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/customer_person.png"))); // NOI18N
        customer_jButton.setText("Customer info");
        customer_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_jButtonActionPerformed(evt);
            }
        });

        contract_jButton.setText("Contracts");
        contract_jButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contract_jButtonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contract_jButtonMouseExited(evt);
            }
        });
        contract_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contract_jButtonActionPerformed(evt);
            }
        });

        export_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EXPORT REPORTS", "Orders", "Declined", "Pending", "Approved", "Gatepass", "Shipping", "Delivered", "Maintenance" }));
        export_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                export_jComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customer_jButton)
                .addGap(145, 145, 145)
                .addComponent(contract_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(Print_jButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(export_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(export_jComboBox)
                    .addComponent(contract_jButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(customer_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Print_jButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void customer_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_jButtonActionPerformed
try {
    jTable1.setShowGrid(true);
            Connection con = DBConn.myConn();
            PreparedStatement stmt1 = con.prepareStatement(" ALTER view loanCoolerView as select   *  , case when approved_by_asm = 0 and approved_by_rsm = 0 THEN 'PENDING' when approved_by_asm = 0 and approved_by_rsm = 1 THEN 'PENDING' when approved_by_asm = 1 and approved_by_rsm = 0 THEN 'PENDING' when approved_by_asm = 1 and approved_by_rsm = 1 THEN 'APPROVED'else 'DECLINED' end cooler_status from loan_coooler");
int rs1 = stmt1.executeUpdate();
System.out.println(rs1+" records affected");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT doc_no,contract_no,outlet_name,outlet_owner,location,street,next_to,route,order_no,recomendations,cooler_status FROM loanCoolerView");
            
            // get columns info
            ResultSetMetaData rsmd = rs.getMetaData();
            int columnCount = rsmd.getColumnCount();
            
            // for changing column and row model
            DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
            
            // clear existing columns 
            tm.setColumnCount(0);
            
            // add specified columns to table
            for (int i = 1; i <= columnCount; i++ ) {
                tm.addColumn(rsmd.getColumnName(i));
            }               
                
            // clear existing rows
            tm.setRowCount(0);
            
            // add rows to table
            while (rs.next()) {
                String[] a = new String[columnCount];
                for(int i = 0; i < columnCount; i++) {
                    a[i] = rs.getString(i+1);
                }
                tm.addRow(a);
            }
            tm.fireTableDataChanged();
                                           DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
headerRenderer.setBackground(new Color(255, 0, 0));

for (int i = 0; i < jTable1.getModel().getColumnCount(); i++) {
        jTable1.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
}
            // Close ResultSet and Statement
            rs.close();
            
        } catch (Exception ex) { 
            JOptionPane.showMessageDialog(this, ex, ex.getMessage(), WIDTH, null);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_customer_jButtonActionPerformed

    private void Print_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_jButtonActionPerformed
 MessageFormat header = new MessageFormat("Print Report");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
    try {
         jTable1.setShowGrid(true);
        jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer);
    } 
    catch (java.awt.print.PrinterAbortException e) {
    }   catch (PrinterException ex) {
            Logger.getLogger(Reports.class.getName()).log(Level.SEVERE, null, ex);
        } // TODO add your handling code here:
    }//GEN-LAST:event_Print_jButtonActionPerformed

    private void contract_jButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contract_jButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_contract_jButtonMouseExited

    private void contract_jButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contract_jButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_contract_jButtonMouseClicked

    private void contract_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contract_jButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contract_jButtonActionPerformed

    private void export_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_export_jComboBoxActionPerformed
 Object item = export_jComboBox.getSelectedItem();
                    if ("Orders".equals(item)) {
                       Orders();
                    } else if ("Declined".equals(item)) {
                     declinedCoolers();
                    }
                    else if ("Pending".equals(item)) {
                    pendingCoolers();
                    }
                    else if ("Approved".equals(item)) {
                        approvedCoolers();
                    }
                     else if ("Gatepass".equals(item)) {
                        Gatepass();
                    }
                      else if ("Shipping".equals(item)) {
                        Shipping();
                    }
                    else if ("Delivered".equals(item)) {
                   deliveredCoolers();
                    }
                    else if ("Maintenance".equals(item)) {
                      defectiveCoolers();
                    }
                    else   {
                    
                      jTable1.repaint();
                    }           // TODO add your handling code here:
    }//GEN-LAST:event_export_jComboBoxActionPerformed

    

    
    
private void Orders(){

 try{
 
            Connection con = DBConn.myConn();
            Statement statement = con.createStatement();
            FileOutputStream fileOut;
            fileOut = new FileOutputStream("All Orders.xls");
            HSSFWorkbook workbook = new HSSFWorkbook();
            HSSFSheet worksheet = workbook.createSheet("All Orders");
            Row row1 = worksheet.createRow((short)0);
            row1.createCell(0).setCellValue("OUTLET OWNER");
            row1.createCell(1).setCellValue("OUTLET NAME");
             row1.createCell(2).setCellValue("OUTLET NUMBER");
              row1.createCell(3).setCellValue("STREET");
               row1.createCell(4).setCellValue("LOCATION/AREA");
                  row1.createCell(5).setCellValue("SALES REP NAME");
            row1.createCell(6).setCellValue("OCCD NAME");
             row1.createCell(7).setCellValue("COOLER STATUS");
             
              
              
            Row row2 ;
           PreparedStatement stmt1 = con.prepareStatement(" CREATE OR REPLACE view loanCoolerView as select   *  , case when approved_by_asm = 0 and approved_by_rsm = 0 THEN 'PENDING' when approved_by_asm = 0 and approved_by_rsm = 1 THEN 'PENDING' when approved_by_asm = 1 and approved_by_rsm = 0 THEN 'PENDING' when approved_by_asm = 1 and approved_by_rsm = 1 THEN 'APPROVED'else 'DECLINED' end cooler_status from loan_coooler");
int rs1 = stmt1.executeUpdate();
System.out.println(rs1+" records affected");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT outlet_owner,outlet_name,outlet_no,street,location,sales_rep_name,occd_name,cooler_status FROM loanCoolerView L JOIN sales_rep S ON L.sales_rep_id = S.sales_rep_id JOIN occd O ON S.occd_id = O.occd_id");
      
            
            while(rs.next()){
                int a = rs.getRow();
                row2 = worksheet.createRow((short)a);
                row2.createCell(0).setCellValue(rs.getString(1));
                row2.createCell(1).setCellValue(rs.getString(2));
                row2.createCell(2).setCellValue(rs.getString(3));
                row2.createCell(3).setCellValue(rs.getString(4));
                row2.createCell(4).setCellValue(rs.getString(5));
                row2.createCell(5).setCellValue(rs.getString(6));
                row2.createCell(6).setCellValue(rs.getString(7));
                row2.createCell(7).setCellValue(rs.getString(8));
               
                
            }
            workbook.write(fileOut);
            fileOut.flush();
            fileOut.close();
            rs.close();
            statement.close();
            con.close();
             JOptionPane.showMessageDialog(null, "Records successful Exported");
           
        }catch(SQLException ex){
            System.out.println(ex);
        }catch(IOException ioe){
            System.out.println(ioe);
        }


}
    

private void declinedCoolers(){

 try{
 
            Connection con = DBConn.myConn();
            Statement statement = con.createStatement();
            FileOutputStream fileOut;
            fileOut = new FileOutputStream("DECLINED.xls");
            HSSFWorkbook workbook = new HSSFWorkbook();
            HSSFSheet worksheet = workbook.createSheet("Declined Coolers");
            Row row1 = worksheet.createRow((short)0);
            row1.createCell(0).setCellValue("OUTLET OWNER");
            row1.createCell(1).setCellValue("OUTLET NAME");
             row1.createCell(2).setCellValue("OUTLET NUMBER");
              row1.createCell(3).setCellValue("STREET");
               row1.createCell(4).setCellValue("LOCATION");
                  row1.createCell(5).setCellValue("SALES REP NAME");
            row1.createCell(6).setCellValue("OCCD NAME");
              row1.createCell(7).setCellValue("REQUEST DATE");
                row1.createCell(8).setCellValue("REJECT REASON");
            
              
            Row row2 ;
            Statement stmt = con.createStatement();
            
            ResultSet rs = stmt.executeQuery("SELECT outlet_owner,outlet_name,outlet_no,street,location,sales_rep_name,occd_name,request_date,reject_reason FROM loan_coooler L JOIN sales_rep S ON L.sales_rep_id = S.sales_rep_id JOIN occd O ON S.occd_id = O.occd_id JOIN rejected_loan_cooler r ON L.ln_col_id = r.loan_cooler_id WHERE approved_by_asm =2 OR approved_by_rsm=2");

            while(rs.next()){
                int a = rs.getRow();
                row2 = worksheet.createRow((short)a);
                row2.createCell(0).setCellValue(rs.getString(1));
                row2.createCell(1).setCellValue(rs.getString(2));
                row2.createCell(2).setCellValue(rs.getString(3));
                row2.createCell(3).setCellValue(rs.getString(4));
                row2.createCell(4).setCellValue(rs.getString(5));
                row2.createCell(5).setCellValue(rs.getString(6));
                row2.createCell(6).setCellValue(rs.getString(7));
                 row2.createCell(7).setCellValue(rs.getString(8));
                  row2.createCell(8).setCellValue(rs.getString(9));
              
                
            }
            workbook.write(fileOut);
            fileOut.flush();
            fileOut.close();
            rs.close();
            statement.close();
            con.close();
             JOptionPane.showMessageDialog(null, "Records successful Exported");
           
        }catch(SQLException ex){
            System.out.println(ex);
        }catch(IOException ioe){
            System.out.println(ioe);
        }


}




private void pendingCoolers(){

 try{
 
            Connection con = DBConn.myConn();
            Statement statement = con.createStatement();
            FileOutputStream fileOut;
            fileOut = new FileOutputStream("PENDING.xls");
            HSSFWorkbook workbook = new HSSFWorkbook();
            HSSFSheet worksheet = workbook.createSheet("Pending Coolers");
            Row row1 = worksheet.createRow((short)0);
            row1.createCell(0).setCellValue("OUTLET OWNER");
            row1.createCell(1).setCellValue("OUTLET NAME");
             row1.createCell(2).setCellValue("OUTLET NUMBER");
              row1.createCell(3).setCellValue("STREET");
               row1.createCell(4).setCellValue("LOCATION");
                row1.createCell(5).setCellValue("SALES REP NAME");
                 row1.createCell(6).setCellValue("OCCD NAME");
                 
            
              
            Row row2 ;
            Statement stmt = con.createStatement();
            
 ResultSet rs = stmt.executeQuery("SELECT outlet_owner,outlet_name,outlet_no,street,location,sales_rep_name,occd_name FROM loan_coooler L JOIN sales_rep S ON L.sales_rep_id = S.sales_rep_id JOIN occd O ON S.occd_id = O.occd_id WHERE approved_by_asm =0 OR approved_by_rsm=0");
            
            while(rs.next()){
                int a = rs.getRow();
                row2 = worksheet.createRow((short)a);
                row2.createCell(0).setCellValue(rs.getString(1));
                row2.createCell(1).setCellValue(rs.getString(2));
                row2.createCell(2).setCellValue(rs.getString(3));
                row2.createCell(3).setCellValue(rs.getString(4));
                row2.createCell(4).setCellValue(rs.getString(5));
                row2.createCell(5).setCellValue(rs.getString(6));
                row2.createCell(6).setCellValue(rs.getString(7));
               
                
            }
            workbook.write(fileOut);
            fileOut.flush();
            fileOut.close();
            rs.close();
            statement.close();
            con.close();
             JOptionPane.showMessageDialog(null, "Records successful Exported");
           
        }catch(SQLException ex){
            System.out.println(ex);
        }catch(IOException ioe){
            System.out.println(ioe);
        }


}



private void approvedCoolers(){

 try{
 
            Connection con = DBConn.myConn();
            Statement statement = con.createStatement();
            FileOutputStream fileOut;
            fileOut = new FileOutputStream("APPROVED.xls");
            HSSFWorkbook workbook = new HSSFWorkbook();
            HSSFSheet worksheet = workbook.createSheet("Approved Coolers");
            Row row1 = worksheet.createRow((short)0);
            
            row1.createCell(0).setCellValue("OUTLET OWNER");
            row1.createCell(1).setCellValue("OUTLET NAME");
             row1.createCell(2).setCellValue("OUTLET NUMBER");
              row1.createCell(3).setCellValue("STREET");
               row1.createCell(4).setCellValue("LOCATION");
                row1.createCell(5).setCellValue("SALES REP NAME");
                 row1.createCell(6).setCellValue("OCCD NAME");
                 
            
              
            Row row2 ;
            Statement stmt = con.createStatement();
            
            ResultSet rs = stmt.executeQuery("SELECT outlet_owner,outlet_name,outlet_no,street,location,sales_rep_name,occd_name FROM loan_coooler L JOIN sales_rep S ON L.sales_rep_id = S.sales_rep_id JOIN occd O ON S.occd_id = O.occd_id WHERE approved_by_asm =1 AND approved_by_rsm=1 AND approved_by_contlr=0");
            
            while(rs.next()){
                int a = rs.getRow();
                row2 = worksheet.createRow((short)a);
                row2.createCell(0).setCellValue(rs.getString(1));
                row2.createCell(1).setCellValue(rs.getString(2));
                row2.createCell(2).setCellValue(rs.getString(3));
                row2.createCell(3).setCellValue(rs.getString(4));
                row2.createCell(4).setCellValue(rs.getString(5));
                  row2.createCell(5).setCellValue(rs.getString(6));
                row2.createCell(6).setCellValue(rs.getString(7));
               
                
            }
            workbook.write(fileOut);
            fileOut.flush();
            fileOut.close();
            rs.close();
            statement.close();
            con.close();
             JOptionPane.showMessageDialog(null, "Records successful Exported");
           
        }catch(SQLException ex){
            System.out.println(ex);
        }catch(IOException ioe){
            System.out.println(ioe);
        }


}



private void deliveredCoolers(){

 try{
 
            Connection con = DBConn.myConn();
            Statement statement = con.createStatement();
            FileOutputStream fileOut;
            fileOut = new FileOutputStream("DELIVERED.xls");
            HSSFWorkbook workbook = new HSSFWorkbook();
            HSSFSheet worksheet = workbook.createSheet("Delivered Coolers");
            Row row1 = worksheet.createRow((short)0);
            row1.createCell(0).setCellValue("COOLER SERIAL");
            row1.createCell(1).setCellValue("COOLER TYPE");
             row1.createCell(2).setCellValue("OUTLET NUMBER");
              row1.createCell(3).setCellValue("OUTLET NAME");
               row1.createCell(4).setCellValue("LOCATION");
 row1.createCell(5).setCellValue("SALES REP NAME");
  row1.createCell(6).setCellValue("OCCD NAME");
                 
            
              
            Row row2 ;
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT v.cooler_sn, L.cooler_type,outlet_no,outlet_name,location,sales_rep_name,occd_name FROM vtrack_release_info v  JOIN loan_coooler L ON v.request_id = L.ln_col_id JOIN sales_rep S ON L.sales_rep_id = S.sales_rep_id JOIN occd O ON S.occd_id = O.occd_id WHERE is_delivered=1");
            
            
            while(rs.next()){
                int a = rs.getRow();
                row2 = worksheet.createRow((short)a);
                row2.createCell(0).setCellValue(rs.getString(1));
                row2.createCell(1).setCellValue(rs.getString(2));
                row2.createCell(2).setCellValue(rs.getString(3));
                row2.createCell(3).setCellValue(rs.getString(4));
                row2.createCell(4).setCellValue(rs.getString(5));
 row2.createCell(5).setCellValue(rs.getString(6));
  row2.createCell(6).setCellValue(rs.getString(7));
               
                
            }
            workbook.write(fileOut);
            fileOut.flush();
            fileOut.close();
            rs.close();
            statement.close();
            con.close();
             JOptionPane.showMessageDialog(null, "Records successful Exported");
           
        }catch(SQLException ex){
            System.out.println(ex);
        }catch(IOException ioe){
            System.out.println(ioe);
        }


}



private void defectiveCoolers(){

 try{
 
            Connection con = DBConn.myConn();
            Statement statement = con.createStatement();
            FileOutputStream fileOut;
            fileOut = new FileOutputStream("DEFECTIVE.xls");
            HSSFWorkbook workbook = new HSSFWorkbook();
            HSSFSheet worksheet = workbook.createSheet("Defective Coolers");
            Row row1 = worksheet.createRow((short)0);
            row1.createCell(0).setCellValue("OUTLET NAME");
            row1.createCell(1).setCellValue("OUTLET NUMBER");
             row1.createCell(2).setCellValue("STREET");
              
               row1.createCell(3).setCellValue("COOLER TYPE");
 row1.createCell(4).setCellValue("SALES REP NAME");
 row1.createCell(5).setCellValue("OCCD NAME");
 row1.createCell(6).setCellValue("COOLER STATUS");
                 
            
              
            Row row2 ;
            PreparedStatement stmt1 = con.prepareStatement(" CREATE OR REPLACE view maintenanceCoolerView as select   *  , case when r_status = 0  THEN 'RECEIVED' when r_status = 1 THEN 'ASSIGNED' when r_status = 2 THEN 'FIXED' end cooler_status FROM cooler_maintenance ");
int rs1 = stmt1.executeUpdate();
System.out.println(rs1+" records affected");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT outlet_name,outlet_no,street,cooler_type,sales_rep_name,occd_name,cooler_status FROM maintenanceCoolerView M JOIN sales_rep S ON M.sales_rep_id = S.sales_rep_id JOIN occd O ON S.occd_id = O.occd_id");
            
            while(rs.next()){
                int a = rs.getRow();
                row2 = worksheet.createRow((short)a);
                row2.createCell(0).setCellValue(rs.getString(1));
                row2.createCell(1).setCellValue(rs.getString(2));
                row2.createCell(2).setCellValue(rs.getString(3));
                row2.createCell(3).setCellValue(rs.getString(4));
                row2.createCell(4).setCellValue(rs.getString(5));
 row2.createCell(5).setCellValue(rs.getString(6));
row2.createCell(6).setCellValue(rs.getString(7));

               
                
            }
            workbook.write(fileOut);
            fileOut.flush();
            fileOut.close();
            rs.close();
            statement.close();
            con.close();
             JOptionPane.showMessageDialog(null, "Records successful Exported");
           
        }catch(SQLException ex){
            System.out.println(ex);
        }catch(IOException ioe){
            System.out.println(ioe);
        }


}



private void Gatepass(){

 try{
 
            Connection con = DBConn.myConn();
            Statement statement = con.createStatement();
            FileOutputStream fileOut;
            fileOut = new FileOutputStream("DEFECTIVE.xls");
            HSSFWorkbook workbook = new HSSFWorkbook();
            HSSFSheet worksheet = workbook.createSheet("Defective Coolers");
            Row row1 = worksheet.createRow((short)0);
            row1.createCell(0).setCellValue("OUTLET OWNER");
            row1.createCell(1).setCellValue("OUTLET NAME");
            row1.createCell(2).setCellValue("OUTLET NUMBER");
      
              
               row1.createCell(3).setCellValue("COOLER TYPE");
                row1.createCell(4).setCellValue("LOCATION");
 row1.createCell(5).setCellValue("SALES REP NAME");
 row1.createCell(6).setCellValue("OCCD NAME");

                 
            
              
            Row row2 ;
           
            Statement stmt = con.createStatement();
            
            ResultSet rs = stmt.executeQuery("SELECT outlet_owner,outlet_name,outlet_no,cooler_type,location,sales_rep_name,occd_name FROM loan_coooler L JOIN sales_rep S ON L.sales_rep_id = S.sales_rep_id JOIN occd O ON S.occd_id = O.occd_id WHERE approved_by_asm =1 AND approved_by_rsm=1 AND approved_by_contlr=1  AND approve_by_fmanager=0");
            
            while(rs.next()){
                int a = rs.getRow();
                row2 = worksheet.createRow((short)a);
                row2.createCell(0).setCellValue(rs.getString(1));
                row2.createCell(1).setCellValue(rs.getString(2));
                row2.createCell(2).setCellValue(rs.getString(3));
                row2.createCell(3).setCellValue(rs.getString(4));
                row2.createCell(4).setCellValue(rs.getString(5));
 row2.createCell(5).setCellValue(rs.getString(6));
row2.createCell(6).setCellValue(rs.getString(7));

               
                
            }
            workbook.write(fileOut);
            fileOut.flush();
            fileOut.close();
            rs.close();
            statement.close();
            con.close();
             JOptionPane.showMessageDialog(null, "Records successful Exported");
           
        }catch(SQLException ex){
            System.out.println(ex);
        }catch(IOException ioe){
            System.out.println(ioe);
        }


}




private void Shipping(){

 try{
 
            Connection con = DBConn.myConn();
            Statement statement = con.createStatement();
            FileOutputStream fileOut;
            fileOut = new FileOutputStream("DEFECTIVE.xls");
            HSSFWorkbook workbook = new HSSFWorkbook();
            HSSFSheet worksheet = workbook.createSheet("Defective Coolers");
            Row row1 = worksheet.createRow((short)0);
            row1.createCell(0).setCellValue("OUTLET OWNER");
            row1.createCell(1).setCellValue("OUTLET NAME");
            row1.createCell(2).setCellValue("OUTLET NUMBER");
      
              
               row1.createCell(3).setCellValue("COOLER TYPE");
                row1.createCell(4).setCellValue("LOCATION");
 row1.createCell(5).setCellValue("SALES REP NAME");
 row1.createCell(6).setCellValue("OCCD NAME");

                 
            
              
            Row row2 ;
           
            Statement stmt = con.createStatement();
            
            ResultSet rs = stmt.executeQuery("SELECT outlet_owner,outlet_name,outlet_no,cooler_type,location,sales_rep_name,occd_name FROM loan_coooler L JOIN sales_rep S ON L.sales_rep_id = S.sales_rep_id JOIN occd O ON S.occd_id = O.occd_id WHERE approved_by_asm =1 AND approved_by_rsm=1 AND approved_by_contlr=1 AND approve_by_fmanager=1");
            
            while(rs.next()){
                int a = rs.getRow();
                row2 = worksheet.createRow((short)a);
                row2.createCell(0).setCellValue(rs.getString(1));
                row2.createCell(1).setCellValue(rs.getString(2));
                row2.createCell(2).setCellValue(rs.getString(3));
                row2.createCell(3).setCellValue(rs.getString(4));
                row2.createCell(4).setCellValue(rs.getString(5));
 row2.createCell(5).setCellValue(rs.getString(6));
row2.createCell(6).setCellValue(rs.getString(7));

               
                
            }
            workbook.write(fileOut);
            fileOut.flush();
            fileOut.close();
            rs.close();
            statement.close();
            con.close();
             JOptionPane.showMessageDialog(null, "Records successful Exported");
           
        }catch(SQLException ex){
            System.out.println(ex);
        }catch(IOException ioe){
            System.out.println(ioe);
        }


}







    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Print_jButton;
    private javax.swing.JButton contract_jButton;
    private javax.swing.JButton customer_jButton;
    private javax.swing.JComboBox<String> export_jComboBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}